version: '3.4'
services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    ports:
      - "8999:8999"
    environment:
      - BACKEND_API=http://test.com
  frontend:
    build:
      target: npm
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FRONTEND_API_LOC=http://localhost:8999/
